# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31e4c9fce05eb88aa30b435ac31bcd0b8f53a44b479d118580fb6d48d4b612af1e5a28f584ed33eed734b281712b0bf9804e94513004a186d7dbec6e0bed0cb2

test:
  secret_key_base: e4025c65e24ea890acf0def0a305fe4c0498f732afaaa61cc0a9f2e2bb06b2ee528a6bd8eb5027207be350c1dd5e944bdd46a7465308b52970b7ebef517fd93a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
